//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseDAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CruiseDAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///
        ///--Core Tables--
        ///--Sale--
        ///CREATE TRIGGER OnUpdateSale 
        ///AFTER UPDATE OF Sale_CN, SaleNumber, Name, Purpose, Region, Forest, District, MeasurementYear, CalendarYear, LogGradingEnabled, Remarks, DefaultUOM 
        ///ON Sale 
        ///BEGIN
        ///	UPDATE Sale 
        ///	SET ModifiedDate = datetime(current_timestamp, &apos;localtime&apos;) 
        ///	WHERE rowID = new.rowID; 
        ///END;
        ///
        /// 
        ///CREATE TRIGGER OnUpdateSaleRowVersion AFTER UPDATE 
        ///OF Sale_CN, SaleNumber, Name, Purpose, Region, Forest, District, MeasurementYear, CalendarYear, LogGradingEnabled [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTriggers {
            get {
                return ResourceManager.GetString("CreateTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///
        ///PRAGMA foreign_keys = ON;--is the nessicary? no data is being inserted yet.
        ///
        ///
        ///--Core Tables--
        ///    CREATE TABLE Sale (
        ///				Sale_CN INTEGER PRIMARY KEY AUTOINCREMENT,
        ///				SaleNumber TEXT NOT NULL,
        ///				Name TEXT,
        ///				Purpose TEXT,
        ///				Region TEXT NOT NULL,
        ///				Forest TEXT NOT NULL,
        ///				District TEXT NOT NULL,
        ///				MeasurementYear TEXT,
        ///				CalendarYear INTEGER Default 0,
        ///				LogGradingEnabled BOOLEAN Default 0,
        ///				Remarks TEXT,
        ///				DefaultUOM TEXT,
        ///				CreatedBy TEXT DEFAULT &apos;none&apos;,
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CruiseCreate {
            get {
                return ResourceManager.GetString("CruiseCreate", resourceCulture);
            }
        }
    }
}
