using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CruiseDAL.Schema
{
    public class FIATableDefinition : ITableDefinition
    {
        public string TableName => "LK_FIA";

        public string CreateTable =>
@"CREATE TABLE LK_FIA (
    LK_FIA_CN INTEGER PRIMARY KEY AUTOINCREMENT,
    FIACode INTEGER NOT NULL,
    CommonName TEXT NOT NULL,

    UNIQUE (FIACode)
);";

        public string InitializeTable =>
@"INSERT INTO LK_FIA 
    (FIACode, CommonName )
VALUES
    ('10', 'fir spp.'),
    ('11', 'Pacific silver fir'),
    ('12', 'balsam fir'),
    ('14', 'Santa Lucia or bristlecone fir'),
    ('15', 'white fir'),
    ('16', 'Fraser fir'),
    ('17', 'grand fir'),
    ('18', 'corkbark fir'),
    ('19', 'subalpine fir'),
    ('20', 'California red fir'),
    ('21', 'Shasta red fir'),
    ('22', 'noble fir'),
    ('40', 'white-cedar spp.'),
    ('41', 'Port-Orford-cedar'),
    ('42', 'Alaska yellow-cedar'),
    ('43', 'Atlantic white-cedar'),
    ('50', 'cypress'),
    ('51', 'Arizona cypress'),
    ('52', 'Baker or Modoc cypress'),
    ('53', 'Tecate cypress'),
    ('54', 'Monterey cypress'),
    ('55', 'Sargent''s cypress'),
    ('56', 'MacNab''s cypress'),
    ('57', 'redcedar/juniper spp.'),
    ('58', 'Pinchot juniper'),
    ('59', 'redberry juniper'),
    ('60', 'drooping juniper'),
    ('61', 'Ashe juniper'),
    ('62', 'California juniper'),
    ('63', 'alligator juniper'),
    ('64', 'western juniper'),
    ('65', 'Utah juniper'),
    ('66', 'Rocky Mountain juniper'),
    ('67', 'southern redcedar'),
    ('68', 'eastern redcedar'),
    ('69', 'oneseed juniper'),
    ('70', 'larch spp.'),
    ('71', 'tamarack (native)'),
    ('72', 'subalpine larch'),
    ('73', 'western larch'),
    ('81', 'incense-cedar'),
    ('90', 'spruce spp.'),
    ('91', 'Norway spruce'),
    ('92', 'Brewer spruce'),
    ('93', 'Engelmann spruce'),
    ('94', 'white spruce'),
    ('95', 'black spruce'),
    ('96', 'blue spruce'),
    ('97', 'red spruce'),
    ('98', 'Sitka spruce'),
    ('100', 'pine spp.'),
    ('101', 'whitebark pine'),
    ('102', 'Rocky Mountain bristlecone pine'),
    ('103', 'knobcone pine'),
    ('104', 'foxtail pine'),
    ('105', 'jack pine'),
    ('106', 'common or two-needle pinyon'),
    ('107', 'sand pine'),
    ('108', 'lodgepole pine'),
    ('109', 'Coulter pine'),
    ('110', 'shortleaf pine'),
    ('111', 'slash pine'),
    ('112', 'Apache pine'),
    ('113', 'limber pine'),
    ('114', 'southwestern white pine'),
    ('115', 'spruce pine'),
    ('116', 'Jeffrey pine'),
    ('117', 'sugar pine'),
    ('118', 'Chihuahuan pine'),
    ('119', 'western white pine'),
    ('120', 'bishop pine'),
    ('121', 'longleaf pine'),
    ('122', 'ponderosa pine'),
    ('123', 'Table Mountain pine'),
    ('124', 'Monterey pine'),
    ('125', 'red pine'),
    ('126', 'pitch pine'),
    ('127', 'gray or California foothill pine'),
    ('128', 'pond pine'),
    ('129', 'eastern white pine'),
    ('130', 'Scotch pine'),
    ('131', 'loblolly pine'),
    ('132', 'Virginia pine'),
    ('133', 'singleleaf pinyon'),
    ('134', 'border pinyon'),
    ('135', 'Arizona pine'),
    ('136', 'Austrian pine'),
    ('137', 'Washoe pine'),
    ('138', 'four-leaf or Parry pinyon pine'),
    ('139', 'Torrey pine'),
    ('140', 'Mexican pinyon pine'),
    ('141', 'papershell pinyon pine'),
    ('142', 'Great Basin bristlecone pine'),
    ('143', 'Arizona pinyon pine'),
    ('144', 'Honduras pine'),
    ('200', 'Douglas-fir spp.'),
    ('201', 'bigcone Douglas-fir'),
    ('202', 'Douglas-fir'),
    ('211', 'redwood'),
    ('212', 'giant sequoia'),
    ('220', 'baldcypress spp.'),
    ('221', 'baldcypress'),
    ('222', 'pondcypress'),
    ('223', 'Montezuma baldcypress'),
    ('230', 'yew spp.'),
    ('231', 'Pacific yew'),
    ('232', 'Florida yew'),
    ('240', 'thuja spp.'),
    ('241', 'northern white-cedar'),
    ('242', 'western redcedar'),
    ('250', 'torreya (nutmeg) spp.'),
    ('251', 'California torreya (nutmeg)'),
    ('252', 'Florida torreya (nutmeg)'),
    ('260', 'hemlock spp.'),
    ('261', 'eastern hemlock'),
    ('262', 'Carolina hemlock'),
    ('263', 'western hemlock'),
    ('264', 'mountain hemlock'),
    ('299', 'Unknown dead conifer'),
    ('300', 'acacia spp.'),
    ('303', 'sweet acacia'),
    ('304', 'catclaw acacia'),
    ('310', 'maple spp.'),
    ('311', 'Florida maple'),
    ('312', 'bigleaf maple'),
    ('313', 'boxelder'),
    ('314', 'black maple'),
    ('315', 'striped maple'),
    ('316', 'red maple'),
    ('317', 'silver maple'),
    ('318', 'sugar maple'),
    ('319', 'mountain maple'),
    ('320', 'Norway maple'),
    ('321', 'Rocky Mountain maple'),
    ('322', 'bigtooth maple'),
    ('323', 'chalk maple'),
    ('330', 'buckeye, horsechestnut spp.'),
    ('331', 'Ohio buckeye'),
    ('332', 'yellow buckeye'),
    ('333', 'California buckeye'),
    ('334', 'Texas buckeye'),
    ('336', 'red buckeye'),
    ('337', 'painted buckeye'),
    ('341', 'ailanthus'),
    ('345', 'mimosa, silktree'),
    ('350', 'alder spp.'),
    ('351', 'red alder'),
    ('352', 'white alder'),
    ('353', 'Arizona alder'),
    ('355', 'European alder'),
    ('356', 'serviceberry spp.'),
    ('357', 'common serviceberry'),
    ('358', 'roundleaf serviceberry'),
    ('360', 'madrone spp.'),
    ('361', 'Pacific madrone'),
    ('362', 'Arizona madrone'),
    ('363', 'Texas madrone'),
    ('367', 'pawpaw'),
    ('370', 'birch spp.'),
    ('371', 'yellow birch'),
    ('372', 'sweet birch'),
    ('373', 'river birch'),
    ('374', 'water birch'),
    ('375', 'paper birch'),
    ('376', 'resin birch'),
    ('377', 'Virginia roundleaf birch'),
    ('378', 'northwestern paper birch'),
    ('379', 'gray birch'),
    ('381', 'chittamwood, gum bumelia'),
    ('391', 'American hornbeam, musclewood'),
    ('400', 'hickory spp.'),
    ('401', 'water hickory'),
    ('402', 'bitternut hickory'),
    ('403', 'pignut hickory'),
    ('404', 'pecan'),
    ('405', 'shellbark hickory'),
    ('406', 'nutmeg hickory'),
    ('407', 'shagbark hickory'),
    ('408', 'black hickory'),
    ('409', 'mockernut hickory'),
    ('410', 'sand hickory'),
    ('411', 'scrub hickory'),
    ('412', 'red hickory'),
    ('413', 'southern shagbark hickory'),
    ('420', 'chestnut spp.'),
    ('421', 'American chestnut'),
    ('422', 'Allegheny chinkapin'),
    ('423', 'Ozark chinkapin'),
    ('424', 'Chinese chestnut'),
    ('431', 'giant chinkapin, golden chinkapin'),
    ('450', 'catalpa spp.'),
    ('451', 'southern catalpa'),
    ('452', 'northern catalpa'),
    ('460', 'hackberry spp.'),
    ('461', 'sugarberry'),
    ('462', 'hackberry'),
    ('463', 'netleaf hackberry'),
    ('471', 'eastern redbud'),
    ('475', 'curlleaf mountain-mahogany'),
    ('481', 'yellowwood'),
    ('490', 'dogwood spp.'),
    ('491', 'flowering dogwood'),
    ('492', 'Pacific dogwood'),
    ('500', 'hawthorn spp.'),
    ('501', 'cockspur hawthorn'),
    ('502', 'downy hawthorn'),
    ('503', 'Brainerd''s hawthorn'),
    ('504', 'pear hawthorn'),
    ('505', 'fireberry hawthorn'),
    ('506', 'broadleaf hawthorn'),
    ('507', 'fanleaf hawthorn'),
    ('508', 'oneseed hawthorn'),
    ('509', 'scarlet hawthorn'),
    ('510', 'eucalyptus spp.'),
    ('511', 'Tasmanian bluegum'),
    ('512', 'river redgum'),
    ('513', 'grand eucalyptus'),
    ('514', 'swampmahogany'),
    ('520', 'persimmon spp.'),
    ('521', 'common persimmon'),
    ('522', 'Texas persimmon'),
    ('523', 'Anacua knockaway'),
    ('531', 'American beech'),
    ('540', 'ash spp.'),
    ('541', 'white ash'),
    ('542', 'Oregon ash'),
    ('543', 'black ash'),
    ('544', 'green ash'),
    ('545', 'pumpkin ash'),
    ('546', 'blue ash'),
    ('547', 'velvet ash'),
    ('548', 'Carolina ash'),
    ('549', 'Texas ash'),
    ('550', 'honeylocust spp.'),
    ('551', 'waterlocust'),
    ('552', 'honeylocust'),
    ('555', 'loblolly-bay'),
    ('561', 'ginkgo, maidenhair tree'),
    ('571', 'Kentucky coffeetree'),
    ('580', 'silverbell spp.'),
    ('581', 'Carolina silverbell'),
    ('582', 'two-wing silverbell'),
    ('583', 'little silverbell'),
    ('591', 'American holly'),
    ('600', 'walnut spp.'),
    ('601', 'butternut'),
    ('602', 'black walnut'),
    ('603', 'northern California black walnut'),
    ('604', 'southern California black walnut'),
    ('605', 'Texas walnut'),
    ('606', 'Arizona walnut'),
    ('611', 'sweetgum'),
    ('621', 'yellow-poplar'),
    ('631', 'tanoak'),
    ('641', 'Osage-orange'),
    ('650', 'magnolia spp.'),
    ('651', 'cucumbertree'),
    ('652', 'southern magnolia'),
    ('653', 'sweetbay'),
    ('654', 'bigleaf magnolia'),
    ('655', 'mountain or Fraser magnolia'),
    ('657', 'pyramid magnolia'),
    ('658', 'umbrella magnolia'),
    ('660', 'apple spp.'),
    ('661', 'Oregon crab apple'),
    ('662', 'southern crab apple'),
    ('663', 'sweet crab apple'),
    ('664', 'prairie crab apple'),
    ('680', 'mulberry spp.'),
    ('681', 'white mulberry'),
    ('682', 'red mulberry'),
    ('683', 'Texas mulberry'),
    ('684', 'black mulberry'),
    ('690', 'tupelo spp.'),
    ('691', 'water tupelo'),
    ('692', 'Ogeechee tupelo'),
    ('693', 'blackgum'),
    ('694', 'swamp tupelo'),
    ('701', 'eastern hophornbeam'),
    ('711', 'sourwood'),
    ('712', 'paulownia, empress-tree'),
    ('720', 'bay spp.'),
    ('721', 'redbay'),
    ('722', 'water-elm, planertree'),
    ('729', 'sycamore spp.'),
    ('730', 'California sycamore'),
    ('731', 'American sycamore'),
    ('732', 'Arizona sycamore'),
    ('740', 'cottonwood and poplar spp.'),
    ('741', 'balsam poplar'),
    ('742', 'eastern cottonwood'),
    ('743', 'bigtooth aspen'),
    ('744', 'swamp cottonwood'),
    ('745', 'plains cottonwood'),
    ('746', 'quaking aspen'),
    ('747', 'black cottonwood'),
    ('748', 'Fremont cottonwood'),
    ('749', 'narrowleaf cottonwood'),
    ('752', 'silver poplar'),
    ('753', 'Lombardy poplar'),
    ('755', 'mesquite spp.'),
    ('756', 'honey mesquite'),
    ('757', 'velvet mesquite'),
    ('758', 'screwbean mesquite'),
    ('760', 'cherry and plum spp.'),
    ('761', 'pin cherry'),
    ('762', 'black cherry'),
    ('763', 'chokecherry'),
    ('764', 'peach'),
    ('765', 'Canada plum'),
    ('766', 'American plum'),
    ('768', 'bitter cherry'),
    ('769', 'Allegheny plum'),
    ('770', 'Chickasaw plum'),
    ('771', 'sweet cherry, domesticated'),
    ('772', 'sour cherry, domesticated'),
    ('773', 'European plum, domesticated'),
    ('774', 'Mahaleb cherry, domesticated'),
    ('800', 'oak spp.'),
    ('801', 'California live oak'),
    ('802', 'white oak'),
    ('803', 'Arizona white oak'),
    ('804', 'swamp white oak'),
    ('805', 'canyon live oak'),
    ('806', 'scarlet oak'),
    ('807', 'blue oak'),
    ('808', 'Durand oak'),
    ('809', 'northern pin oak'),
    ('810', 'Emory oak'),
    ('811', 'Engelmann oak'),
    ('812', 'southern red oak'),
    ('813', 'cherrybark oak'),
    ('814', 'Gambel oak'),
    ('815', 'Oregon white oak'),
    ('816', 'scrub oak'),
    ('817', 'shingle oak'),
    ('818', 'California black oak'),
    ('819', 'turkey oak'),
    ('820', 'laurel oak'),
    ('821', 'California white oak'),
    ('822', 'overcup oak'),
    ('823', 'bur oak'),
    ('824', 'blackjack oak'),
    ('825', 'swamp chestnut oak'),
    ('826', 'chinkapin oak'),
    ('827', 'water oak'),
    ('828', 'Texas red oak'),
    ('829', 'Mexican blue oak'),
    ('830', 'pin oak'),
    ('831', 'willow oak'),
    ('832', 'chestnut oak'),
    ('833', 'northern red oak'),
    ('834', 'Shumard oak'),
    ('835', 'post oak'),
    ('836', 'Delta post oak'),
    ('837', 'black oak'),
    ('838', 'live oak'),
    ('839', 'interior live oak'),
    ('840', 'dwarf post oak'),
    ('841', 'dwarf live oak'),
    ('842', 'bluejack oak'),
    ('843', 'silverleaf oak'),
    ('844', 'Oglethorpe oak'),
    ('845', 'dwarf chinkapin oak'),
    ('846', 'gray oak'),
    ('847', 'netleaf oak'),
    ('851', 'Chisos oak'),
    ('852', 'sea torchwood'),
    ('853', 'pond-apple'),
    ('854', 'gumbo limbo'),
    ('855', 'sheoak spp.'),
    ('856', 'gray sheoak'),
    ('857', 'belah'),
    ('858', 'camphortree'),
    ('859', 'Florida fiddlewood'),
    ('860', 'citrus spp.'),
    ('863', 'tietongue, pigeon-plum'),
    ('864', 'soldierwood'),
    ('865', 'largeleaf geigertree'),
    ('866', 'carrotwood'),
    ('867', 'bluewood'),
    ('868', 'blackbead ebony'),
    ('869', 'great leucaene'),
    ('870', 'Texas sophora'),
    ('873', 'red stopper'),
    ('874', 'butterbough, inkwood'),
    ('876', 'Florida strangler fig'),
    ('877', 'wild banyantree, shortleaf fig'),
    ('882', 'beeftree, longleaf blolly'),
    ('883', 'manchineel'),
    ('884', 'false tamarind'),
    ('885', 'mango'),
    ('886', 'Florida poisontree'),
    ('887', 'fishpoison tree'),
    ('888', 'octopus tree, schefflera'),
    ('890', 'false mastic'),
    ('891', 'white bully, willow bustic'),
    ('895', 'paradisetree'),
    ('896', 'Java plum'),
    ('897', 'tamarind'),
    ('901', 'black locust'),
    ('902', 'New Mexico locust'),
    ('906', 'Everglades palm, paurotis-palm'),
    ('907', 'Florida silver palm'),
    ('908', 'coconut palm'),
    ('909', 'royal palm spp.'),
    ('911', 'Mexican palmetto'),
    ('912', 'cabbage palmetto'),
    ('913', 'key thatch palm'),
    ('914', 'Florida thatch palm'),
    ('915', 'other palms'),
    ('919', 'western soapberry'),
    ('920', 'willow spp.'),
    ('921', 'peachleaf willow'),
    ('922', 'black willow'),
    ('923', 'Bebb willow'),
    ('924', 'Bonpland willow'),
    ('925', 'coastal plain willow'),
    ('926', 'balsam willow'),
    ('927', 'white willow'),
    ('928', 'Scouler''s willow'),
    ('929', 'weeping willow'),
    ('931', 'sassafras'),
    ('934', 'mountain-ash spp.'),
    ('935', 'American mountain-ash'),
    ('936', 'European mountain-ash'),
    ('937', 'northern mountain-ash'),
    ('940', 'West Indian mahogany'),
    ('950', 'basswood spp.'),
    ('951', 'American basswood'),
    ('952', 'white basswood'),
    ('953', 'Carolina basswood'),
    ('970', 'elm spp.'),
    ('971', 'winged elm'),
    ('972', 'American elm'),
    ('973', 'cedar elm'),
    ('974', 'Siberian elm'),
    ('975', 'slippery elm'),
    ('976', 'September elm'),
    ('977', 'rock elm'),
    ('981', 'California-laurel'),
    ('982', 'Joshua tree'),
    ('986', 'black-mangrove'),
    ('987', 'buttonwood-mangrove'),
    ('988', 'white-mangrove'),
    ('989', 'American mangrove'),
    ('990', 'desert ironwood'),
    ('991', 'saltcedar'),
    ('992', 'melaleuca'),
    ('993', 'chinaberry'),
    ('994', 'Chinese tallowtree'),
    ('995', 'tungoil tree'),
    ('996', 'smoketree'),
    ('997', 'Russian-olive'),
    ('998', 'Unknown dead hardwood'),
    ('999', 'Other or unknown live tree'),
    ('5091', 'Washington hawthorn'),
    ('5092', 'fleshy hawthorn'),
    ('5093', 'dwarf hawthorn'),
    ('5491', 'Berlandier ash'),
    ('7211', 'avocado'),
    ('8420', 'pear'),
    ('8511', 'Graves oak'),
    ('8512', 'Mexican white oak'),
    ('8513', 'Buckley oak'),
    ('8514', 'Lacey oak'),
    ('8651', 'Texas olive');";

        public string CreateTombstoneTable => null;

        public string CreateIndexes => null;

        public IEnumerable<string> CreateTriggers => Enumerable.Empty<string>();
    }
}
