using System;
using System.Collections.Generic;

namespace CruiseDAL.Schema
{
    public static partial class Migrations
    {
        private static string[] MIGRATION_FORMAT_STRINGS = new string[]
        {
            MIGRATE_SALE_FORMAT_STR,
            MIGRATE_CUTTINGUNIT_FORMAT_STR,
            MIGRATE_STRATUM_FORMAT_STR,
            MIGRATE_CUTTINGUNIT_STRATUM_FROM_CUTTINGUNITSTRATUM,
            MIGRATE_SAMPLEGROUP_FROM_SAMPLEGROUP,
            //MIGRATE_SAMPLERSTATE_FROM_SAMPLEGROUP_FORMAT_STR,
            MIGRATE_PLOT_FROM_PLOT_FORMAT_STR,
            MIGRATE_PLOT_STRATUM_FROM_PLOT_FORMAT_STR,
            MIGRATE_SPECIESCODE_FROM_TREEDEFAULTVALUE,
            MIGRATE_SUBPOPULATION_FROM_SAMPLEGROUPTREEDEFAULTVALUE,
            //MIGRATE_TALLYPOPULATION_FROM_COUNTTREE_FORMAT_STR,
            MIGRATE_TREEDEFAULTVALUE_FORMAT_STR,
            MIGRATE_FIXCNTTALLYCLASS_FORMAT_STR,
            MIGRATE_FIXCNTTALLYPOPULATION,

            MIGRATE_TREE_FROM_TREE,
            MIGRATE_TREEMEASURMENT_FROM_TREE_FORMAT_STR,
            MIGRATE_LOG_FROM_LOG,
            MIGRATE_TALLYLEDGER_FROM_COUNTTREE_FORMAT_STR,
            MIGRATE_TALLYLEDGER_FROM_TREE,

            MIGRATE_LOGFIELDSETUP_FROM_LOGFIELDSETUP,
            MIGRATE_TREEFIELDSETUP_FROM_TREEFIELDSETUP_FORMAT_STR,
            MIGRATE_LOGFIELDSETUPDEFAULT_FORMAT_STR,
            MIGRATE_TREEFIELDSETUPDEFAULT_FORMAT_STR,

            MIGRATE_TALLYDESCRIPTION_FROM_COUNTTREE_FORMAT_STR,
            MIGRATE_TALLYHOTKEY_FROM_COUNTTREE_FORMAT_STR,

            MIGRATE_TABLE_Reports,
            MIGRATE_TABLE_LOGMATRIX,
            MIGRATE_TABLE_BIOMASSEQUATION,
            MIGRATE_TABLE_VOLUMEEQUATION,
            MIGRATE_TABLE_VALUEEQUATION,
            MIGRATE_TABLE_QUALITYADJEQUATION,

            MIGRATE_GLOBALS_FORMAT_STR,
            MIGRATE_MESSAGELOG_FORMAT_STR,

            MIGRATE_LOGGRADEAUDITRULE,
            MIGRATE_TREEAUDITRULE_FROM_TREEAUDITVALUE_FORMAT_STR,
            MIGRATE_TREEDEFAULTVALUE_TREEAUDITVALUE_FROM_TREEDEFAULTVALUETREEAUDITVALUE,
        };

        public static IEnumerable<string> GetMigrateCommands(string to, string from)
        {
            var saleID = Guid.NewGuid().ToString();
            var cruiseID = Guid.NewGuid().ToString();
            foreach (var str in MIGRATION_FORMAT_STRINGS)
            {
                yield return string.Format(str, to, from, saleID, cruiseID);
            }
        }
    }
}